### ISSUE TITLE
Upsert fails when trying to import non-unique rows

### ISSUE THREAD

**Issue by avishai** [theSteveMitchell/postgres_upsert#13]
I am trying to import a file which contains duplicate rows. Instead of updating subsequent records, I get this error:

```
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_dealers_on_source_id_and_source_dealer_id"
DETAIL:  Key (source_id, source_dealer_id)=(2, 236) already exists.

```

Shouldn't a duplicate key get updated instead of throwing this error?

**Comment by theSteveMitchell** [comment]
Yes maybe it should, though that's not really the direction we've gone.  For inserting new records, this is hard because "insert into X from temp_x where not exists id" doesn't support having duplicates in the temp table.

the update operation does handle that okay, but we have a check in place that makes sure a CSV with 500 rows results in (#rows inserted + #rows updated) = 500.  That logic fails when you have duplicates, because duplicated rows with "collapsed" in the update. https://github.com/theSteveMitchell/postgres_upsert/blob/master/lib/postgres_upsert/writer.rb#L53

So 2 problems are:
1. we need to make the insert operation only insert the first of the dupes, then update all others (gross)
2. we need a validity check to ensure the expected number of rows were upserted.  That means we have to count all the duplicates.
3. Do these 2 things without hurting performance

Why does the file need to have duplicates within itself?

**Comment by avishai** [comment]
@theSteveMitchell, it's probably better to just exclude the duplicates from the imported CSV to begin with, which is what I've gone with too. I think we can mark this as closed.
